module.exports = {
  AutocompleteItemTemplate: require("./AutocompleteItemTemplate.jsx"),
  ButtonTemplate: require("./ButtonTemplate.jsx"),
  ButtonsTemplate: require("./ButtonsTemplate.jsx"),
  CheckboxTemplate: require("./CheckboxTemplate.jsx"),
  CheckboxesGroupTemplate: require("./CheckboxesGroupTemplate.jsx"),
  CheckboxesTemplate: require("./CheckboxesTemplate.jsx"),
  CollectionCreateTemplate: require("./CollectionCreateTemplate.jsx"),
  EditorTemplate: require("./EditorTemplate.jsx"),
  FieldSetTemplate: require("./FieldSetTemplate.jsx"),
  FormTemplate: require("./FormTemplate.jsx"),
  ItemToStringTemplate: require("./ItemToStringTemplate.jsx"),
  ListItemMixin: require("./ListItemMixin.js"),
  ListItemTemplate: require("./ListItemTemplate.jsx"),
  ListTemplate: require("./ListTemplate.jsx"),
  ObjectTemplate: require("./ObjectTemplate.jsx"),
  RadioItemTemplate: require("./RadioItemTemplate.jsx"),
  SimpleTemplate: require("./SimpleTemplate.jsx"),
  WizardProgressTemplate: require("./WizardProgressTemplate.jsx"),
  WizardTemplate: require("./WizardTemplate.jsx"),
}