module.exports = {
  Autocomplete: require('./Autocomplete.js'),
  Checkbox: require('./Checkbox.js'),
  Checkboxes: require('./Checkboxes.js'),
  CollectionMixin: require('./CollectionMixin.js'),
  CreateItemMixin: require('./CreateItemMixin.js'),
  Date: require('./Date.js'),
  DateTime: require('./DateTime.js'),
  Hidden: require('./Hidden.js'),
  LazyType: require('./LazyType.js'),
  List: require('./List.js'),
  Mixed: require('./Mixed.js'),
  Number: require('./Number.js'),
  Object: require('./Object.js'),
  Password: require('./Password.js'),
  Radio: require('./Radio.js'),
  Restricted: require('./Restricted.js'),
  Select: require('./Select.js'),
  Text: require('./Text.js'),
  TextArea: require('./TextArea.js')
}
